"""
src/tracking/backends/yolo.py

Author
------
dolby228 : original implementation (2026-02-05)
KrutayaBabka : refactoring and documentation (2026-02-12)

Description
-----------
Backend adapter for using Ultralytics YOLO models within the multi-object
tracking framework.

This class wraps a YOLO model instance and provides a `track` method
that returns a structured `TrackedObjects` instance compatible with
the internal tracking pipeline. Tracker configurations (e.g., BoTSORT)
are applied via a YAML file generated by the `BackendConfigFactory`.
"""


from pathlib import Path
from ultralytics.models.yolo import YOLO

from .base import TrackingBackend
from src.tracking.config import TrackerConfig

from cv2.typing import MatLike
from src.tracking.types import TrackedObjects


class YoloBackend(TrackingBackend):
    """
    YOLO backend implementation for object detection and tracking.

    Wraps an Ultralytics YOLO model and integrates with a tracker
    configuration (e.g., BoTSORT) to perform detection and multi-object
    tracking. Returns results in the internal `TrackedObjects` format.

    Parameters
    ----------
    config : TrackerConfig
        Tracker configuration specifying model, task type, thresholds,
        inference options, and tracking parameters.
    tracker : Path
        Path to the YAML tracker configuration file. Used to initialize
        the YOLO tracker component (BoTSORT, ByteTrack, etc.).
    """

    def __init__(
        self,
        config: TrackerConfig,
        tracker: Path
    ):
        self.config = config
        self.tracker = tracker

        # Initialize YOLO model for the specified task
        self.model = YOLO(
            model=self.config.model, #type: ignore
            task=self.config.task,
            verbose=self.config.verbose
        )


    def track(self, frame: MatLike) -> TrackedObjects:
        """
        Perform detection and tracking on a single frame.

        Parameters
        ----------
        frame : MatLike
            Input image or video frame to perform detection/tracking on.
            Can be a numpy array representing a single image.

        Returns
        -------
        TrackedObjects
            Structured container of detected/tracked objects for the frame.
            Attributes:
            - `objects` : List[Object], each containing:
                - `cls_id` : int, numeric class ID
                - `cls_name` : str, human-readable class name
                - `conf` : float, detection/tracking confidence
                - `id` : int | None, tracking ID if available
                - `box` : Box, bounding box coordinates (pt1, pt2)
            - `orig_shape` : Tuple[int, int], original frame shape (height, width)
            - `raw_data` : numpy.ndarray | None, raw model output (if available)

        Notes
        -----
        - Delegates to the YOLO `track` function and applies the current
          `TrackerConfig`.
        - The `tracker` argument passed in the constructor is used by YOLO
          for initializing the tracker component (BoTSORT/ByteTrack).
        - Converts YOLO `Results` into `TrackedObjects` for consistent
          internal representation.
        """

        results = self.model.track( #type: ignore
            source=frame,

            stream=self.config.stream,
            persist=self.config.persist,
            verbose=self.config.verbose,

            tracker=self.tracker,
            classes=self.config.classes,
            device=self.config.device,
            augment=self.config.augment,
            agnostic_nms=self.config.agnostic_nms,
            retina_masks=self.config.retina_masks,
            iou=self.config.iou,
            conf=self.config.conf,
            half=self.config.half,
            rect=self.config.rect,
            imgsz=self.config.imgsz
        )
        
        # Convert YOLO Results to internal TrackedObjects format
        # results may be a list of length 1 for single-frame input
        return list(map(TrackedObjects.from_results, results))[0]
        