"""
src/tracking/backends/yolo.py

Author
------
dolby228 : original implementation (2026-02-05)
KrutayaBabka : refactoring and documentation (2026-02-12)

Description
-----------
Backend adapter for using Ultralytics YOLO models with the multi-object
tracking framework. 

This class wraps a YOLO model instance and provides a `track` method
that returns a list of `TrackedObject` instances compatible with
the tracking pipeline. It supports tracker configurations (e.g., BoTSORT)
via a YAML file generated by the `BackendConfigFactory`.
"""


from typing import List
from src.tracking.types import TrackedObject
from .base import TrackingBackend
from src.tracking.config import TrackerConfig
from cv2.typing import MatLike
from pathlib import Path
from ultralytics.models.yolo import YOLO


class YoloBackend(TrackingBackend):
    """
    YOLO backend implementation for object tracking.

    Wraps the Ultralytics YOLO model and integrates it with a tracking
    configuration to perform detection and optionally tracking.

    Parameters
    ----------
    config : TrackerConfig
        Configuration object containing model, thresholds, inference
        options, and tracking parameters.
    tracker : Path
        Path to the YAML tracker configuration file. Used by YOLO to
        initialize the tracker component (e.g., BoTSORT, ByteTrack).
    """

    def __init__(
        self,
        config: TrackerConfig,
        tracker: Path
    ):
        self.config = config
        self.tracker = tracker

        # Initialize YOLO model for the specified task
        self.model = YOLO(
            model=self.config.model, #type: ignore
            task=self.config.task,
            verbose=self.config.verbose
        )


    def track(self, frame: MatLike) -> List[TrackedObject]:
        """
        Perform tracking on a single image or video frame.

        Parameters
        ----------
        frame : MatLike
            Input image or video frame to perform detection/tracking on.
            Can be a numpy array representing a single image.

        Returns
        -------
        List[TrackedObject]
            List of tracked objects detected in the frame. Each object
            includes bounding boxes, masks, probabilities, keypoints,
            orientation, speed estimates, and optional re-identification
            metadata.

        Notes
        -----
        - This method wraps the `YOLO.track` function and applies the
          current `TrackerConfig`.
        - The `tracker` argument provided in the constructor is passed
          to the YOLO tracker (e.g., BoTSORT YAML config).
        """

        results = self.model.track( #type: ignore
            source=frame,

            stream=self.config.stream,
            persist=self.config.persist,
            verbose=self.config.verbose,

            tracker=self.tracker,
            classes=self.config.classes,
            device=self.config.device,
            augment=self.config.augment,
            agnostic_nms=self.config.agnostic_nms,
            retina_masks=self.config.retina_masks,
            iou=self.config.iou,
            conf=self.config.conf,
            half=self.config.half,
            rect=self.config.rect,
            imgsz=self.config.imgsz
        )
        
        # Convert YOLO Results to TrackedObject instances
        return list(map(TrackedObject.from_results, results))
        