import cv2
from enum import IntEnum

class CameraProperty(IntEnum):
    POS_MSEC = cv2.CAP_PROP_POS_MSEC
    POS_FRAMES = cv2.CAP_PROP_POS_FRAMES
    POS_AVI_RATIO = cv2.CAP_PROP_POS_AVI_RATIO
    FRAME_WIDTH = cv2.CAP_PROP_FRAME_WIDTH
    FRAME_HEIGHT = cv2.CAP_PROP_FRAME_HEIGHT
    FPS = cv2.CAP_PROP_FPS
    FOURCC = cv2.CAP_PROP_FOURCC
    FRAME_COUNT = cv2.CAP_PROP_FRAME_COUNT
    FORMAT = cv2.CAP_PROP_FORMAT
    MODE = cv2.CAP_PROP_MODE

    BRIGHTNESS = cv2.CAP_PROP_BRIGHTNESS
    CONTRAST = cv2.CAP_PROP_CONTRAST
    SATURATION = cv2.CAP_PROP_SATURATION
    HUE = cv2.CAP_PROP_HUE
    GAIN = cv2.CAP_PROP_GAIN
    EXPOSURE = cv2.CAP_PROP_EXPOSURE
    CONVERT_RGB = cv2.CAP_PROP_CONVERT_RGB

    WHITE_BALANCE_BLUE_U = cv2.CAP_PROP_WHITE_BALANCE_BLUE_U
    RECTIFICATION = cv2.CAP_PROP_RECTIFICATION
    MONOCHROME = cv2.CAP_PROP_MONOCHROME
    SHARPNESS = cv2.CAP_PROP_SHARPNESS
    AUTO_EXPOSURE = cv2.CAP_PROP_AUTO_EXPOSURE
    GAMMA = cv2.CAP_PROP_GAMMA
    TEMPERATURE = cv2.CAP_PROP_TEMPERATURE

    TRIGGER = cv2.CAP_PROP_TRIGGER
    TRIGGER_DELAY = cv2.CAP_PROP_TRIGGER_DELAY
    WHITE_BALANCE_RED_V = cv2.CAP_PROP_WHITE_BALANCE_RED_V

    ZOOM = cv2.CAP_PROP_ZOOM
    FOCUS = cv2.CAP_PROP_FOCUS
    GUID = cv2.CAP_PROP_GUID
    ISO_SPEED = cv2.CAP_PROP_ISO_SPEED
    BACKLIGHT = cv2.CAP_PROP_BACKLIGHT

    PAN = cv2.CAP_PROP_PAN
    TILT = cv2.CAP_PROP_TILT
    ROLL = cv2.CAP_PROP_ROLL
    IRIS = cv2.CAP_PROP_IRIS
    SETTINGS = cv2.CAP_PROP_SETTINGS
    BUFFERSIZE = cv2.CAP_PROP_BUFFERSIZE
    AUTOFOCUS = cv2.CAP_PROP_AUTOFOCUS

    SAR_NUM = cv2.CAP_PROP_SAR_NUM
    SAR_DEN = cv2.CAP_PROP_SAR_DEN
    BACKEND = cv2.CAP_PROP_BACKEND
    CHANNEL = cv2.CAP_PROP_CHANNEL
    AUTO_WB = cv2.CAP_PROP_AUTO_WB
    WB_TEMPERATURE = cv2.CAP_PROP_WB_TEMPERATURE

    CODEC_PIXEL_FORMAT = cv2.CAP_PROP_CODEC_PIXEL_FORMAT
    BITRATE = cv2.CAP_PROP_BITRATE

    ORIENTATION_META = cv2.CAP_PROP_ORIENTATION_META
    ORIENTATION_AUTO = cv2.CAP_PROP_ORIENTATION_AUTO

    HW_ACCELERATION = cv2.CAP_PROP_HW_ACCELERATION
    HW_DEVICE = cv2.CAP_PROP_HW_DEVICE
    HW_ACCELERATION_USE_OPENCL = cv2.CAP_PROP_HW_ACCELERATION_USE_OPENCL

    OPEN_TIMEOUT_MSEC = cv2.CAP_PROP_OPEN_TIMEOUT_MSEC
    READ_TIMEOUT_MSEC = cv2.CAP_PROP_READ_TIMEOUT_MSEC
    STREAM_OPEN_TIME_USEC = cv2.CAP_PROP_STREAM_OPEN_TIME_USEC

    VIDEO_TOTAL_CHANNELS = cv2.CAP_PROP_VIDEO_TOTAL_CHANNELS
    VIDEO_STREAM = cv2.CAP_PROP_VIDEO_STREAM
    AUDIO_STREAM = cv2.CAP_PROP_AUDIO_STREAM
    AUDIO_POS = cv2.CAP_PROP_AUDIO_POS
    AUDIO_SHIFT_NSEC = cv2.CAP_PROP_AUDIO_SHIFT_NSEC
    AUDIO_DATA_DEPTH = cv2.CAP_PROP_AUDIO_DATA_DEPTH
    AUDIO_SAMPLES_PER_SECOND = cv2.CAP_PROP_AUDIO_SAMPLES_PER_SECOND
    AUDIO_BASE_INDEX = cv2.CAP_PROP_AUDIO_BASE_INDEX
    AUDIO_TOTAL_CHANNELS = cv2.CAP_PROP_AUDIO_TOTAL_CHANNELS
    AUDIO_TOTAL_STREAMS = cv2.CAP_PROP_AUDIO_TOTAL_STREAMS
    AUDIO_SYNCHRONIZE = cv2.CAP_PROP_AUDIO_SYNCHRONIZE

    LRF_HAS_KEY_FRAME = cv2.CAP_PROP_LRF_HAS_KEY_FRAME
    CODEC_EXTRADATA_INDEX = cv2.CAP_PROP_CODEC_EXTRADATA_INDEX
    FRAME_TYPE = cv2.CAP_PROP_FRAME_TYPE
    N_THREADS = cv2.CAP_PROP_N_THREADS
    PTS = cv2.CAP_PROP_PTS
    DTS_DELAY = cv2.CAP_PROP_DTS_DELAY


class ApiPreference(IntEnum):
    ANY = cv2.CAP_ANY
    VFW = cv2.CAP_VFW
    V4L = cv2.CAP_V4L
    V4L2 = cv2.CAP_V4L2
    FIREWIRE = cv2.CAP_FIREWIRE
    FIREWARE = cv2.CAP_FIREWARE
    IEEE1394 = cv2.CAP_IEEE1394
    DC1394 = cv2.CAP_DC1394
    CMU1394 = cv2.CAP_CMU1394
    QT = cv2.CAP_QT
    UNICAP = cv2.CAP_UNICAP
    DSHOW = cv2.CAP_DSHOW
    PVAPI = cv2.CAP_PVAPI
    OPENNI = cv2.CAP_OPENNI
    OPENNI_ASUS = cv2.CAP_OPENNI_ASUS
    ANDROID = cv2.CAP_ANDROID
    XIAPI = cv2.CAP_XIAPI
    AVFOUNDATION = cv2.CAP_AVFOUNDATION
    GIGANETIX = cv2.CAP_GIGANETIX
    MSMF = cv2.CAP_MSMF
    WINRT = cv2.CAP_WINRT
    INTELPERC = cv2.CAP_INTELPERC
    REALSENSE = cv2.CAP_REALSENSE
    OPENNI2 = cv2.CAP_OPENNI2
    OPENNI2_ASUS = cv2.CAP_OPENNI2_ASUS
    OPENNI2_ASTRA = cv2.CAP_OPENNI2_ASTRA
    GPHOTO2 = cv2.CAP_GPHOTO2
    GSTREAMER = cv2.CAP_GSTREAMER
    FFMPEG = cv2.CAP_FFMPEG
    IMAGES = cv2.CAP_IMAGES
    ARAVIS = cv2.CAP_ARAVIS
    OPENCV_MJPEG = cv2.CAP_OPENCV_MJPEG
    INTEL_MFX = cv2.CAP_INTEL_MFX
    XINE = cv2.CAP_XINE
    UEYE = cv2.CAP_UEYE
    OBSENSOR = cv2.CAP_OBSENSOR
    